# Generated by Django 5.1.5 on 2025-01-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crud_Ajax', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cruduser',
            new_name='T_users',
        ),
    ]
