# Generated by Django 5.1.5 on 2025-01-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crud_Ajax', '0002_rename_cruduser_t_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_users',
            old_name='direccion',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='t_users',
            old_name='edad',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='t_users',
            old_name='nombre',
            new_name='name',
        ),
    ]
