# Generated by Django 5.1.5 on 2025-01-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crud_Ajax', '0003_rename_direccion_t_users_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_users',
            old_name='address',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='t_users',
            old_name='age',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='t_users',
            old_name='name',
            new_name='nombre',
        ),
    ]
